# Generated by Django 5.0.1 on 2024-02-11 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=100, unique=True)),
                ('description_product', models.TextField()),
                ('category_product', models.CharField(choices=[('', ''), ('food', 'Food'), ('drink', 'Drink'), ('fruit', 'Fruit'), ('ice_cream', 'Ice Cream'), ('raw_food', 'Raw Food'), ('man_clothes', 'Man Clothes'), ('man_accesories', 'Man Accesories'), ('woman_clothes', 'Woman Clothes'), ('woman_accesories', 'Woman Accesories'), ('hat', 'Hat'), ('shoes', 'Shoes'), ('motorcycle_and_accesories', 'Motorcycle and Accesories'), ('car_and_accesories', 'Car and Accesories'), ('helmet_and_accesories', 'Helmet and Accesories'), ('electronic', 'Electronic'), ('handphone_and_accesories', 'Handphone and Accesories'), ('laptop_and_accesories', 'Laptop and Accesories'), ('computer_and_accesories', 'Computer and Accesories'), ('skincare', 'Skincare'), ('makeup', 'Makeup'), ('basic_needs', 'Basic Needs'), ('voucher_and_phonecredit', 'Voucher and Phonecredit'), ('top_up_games', 'Top Up Games'), ('home_decoration', 'Home Decoration')], default='', max_length=100)),
                ('price_product', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_product', models.IntegerField()),
                ('kind', models.CharField(choices=[('', ''), ('new', 'New'), ('former', 'Former')], default='', max_length=50)),
                ('pre_order', models.BooleanField(default='False')),
                ('pre_order_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.store')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_image', models.ImageField(upload_to='product_images/')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpesification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Spesification', models.CharField(max_length=50)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='SpesificationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_value', models.CharField(max_length=50)),
                ('spesification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productspesification')),
            ],
        ),
    ]
