# Generated by Django 5.0.1 on 2024-02-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pre_order_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
