# Generated by Django 5.0.1 on 2024-02-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_pre_order_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pre_order',
        ),
    ]
