# Generated by Django 5.0.1 on 2024-02-11 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_email_address_alter_store_location_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='location_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=155, unique=True),
        ),
    ]
