# Generated by Django 5.0.1 on 2024-02-11 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_store_location_store_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='location_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='store',
            name='open_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
