# Generated by Django 5.0.1 on 2024-02-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_store_location_store_alter_store_open_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='email_store',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone_number_store',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
