# Generated by Django 5.0.1 on 2024-02-11 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_order', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('pre_order', models.BooleanField(default='False')),
                ('pre_order_time', models.DateTimeField()),
                ('spesification', models.CharField(max_length=100)),
                ('spesificationvalue', models.CharField(max_length=100)),
                ('notes_product', models.TextField(null=True)),
                ('notes_address', models.TextField(null=True)),
                ('shipping_information', models.CharField(default='Waiting Seller Approved', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.store')),
                ('address_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.address')),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
