# Generated by Django 5.0.1 on 2024-02-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pre_order',
        ),
        migrations.AlterField(
            model_name='order',
            name='pre_order_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
