# Generated by Django 5.0.1 on 2024-02-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_pre_order_alter_order_pre_order_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Store_id',
            new_name='store_id',
        ),
    ]
